version: '3'

services:

  tagbox:
    image: machinebox/tagbox
    environment:
      - MB_KEY=${MB_KEY}
    ports:
      - "8888:8080"

  apache:                          
    image: 'bitnami/apache:latest' 
    ports:                         
      - '8080:8080'                
      - '8443:8443'                
    volumes:                       
      - ./apache:/app              
